name: CI

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: examplenode-dev
  DOCKER_HUB_USER: asanio06
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: displayBranch
      if: ${{ github.ref_type == 'branch' }}
      run: |
        - echo "${{ github.sha }}"
        - echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

    - name: displayTag
      if: ${{ github.ref_type == 'tag' }}
      run: |
        - echo echo "${{ github.ref_name }}"
        - echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_HUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_PAT }}
        repository: ${{ github.actor }}/gitops-config
        event-type: new-image
        client-payload: '{"image": "${{ env.DOCKER_HUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"}'